project:
  type: website
  pre-render:
    - "npm run build:docs"

website:
  site-url: https://ruralinnovation.github.io/cori.data.api
  title: "@cori-risi/cori.data.api"
  navbar:
    logo-href: https://ruralinnovation.us/our-work/research_mapping/
    left:
      - href: index.qmd
        text: Frontend UI library
      - href: about.qmd
        text: About
      - href: docs/globals.md
        text: Reference
      - icon: github
        href: https://github.com/ruralinnovation/cori.data.api
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "React components"
        contents:
#          - docs/functions/Button.md
#          - docs/functions/Input.md
#          - docs/functions/Label.md
          - docs/functions/CategoricalLegend.md
          - docs/functions/GeocoderControl.md
          - docs/functions/HoverInfo.md
#          - docs/functions/LineChart.md
          - docs/functions/SSOAuthenticator.md
      - section: "React contexts"
        contents:
          - docs/functions/AmplifyContextProvider.md
          - docs/functions/ApiContextProvider.md
      - section: "Mapbox"
        contents:
          - docs/functions/mapboxGeocode.md
          - docs/variables/coriLightMapStyle.md

format:
  html:
    theme:
      - minty
      - src/custom.scss
    css: assets/fonts.css
    fontcolor: "#121E22"
    linkcolor: "#00835D"
    mainfont: "Bitter"
    grid:
      sidebar-width: 250px
      body-width: 1100px
      margin-width: 250px
    toc: true

resources:
- "assets/*"

execute:
  freeze: auto
